version: "3.8"

services:
  web:
    build:
      context: ./php
    container_name: ${PHP_CONTAINER_NAME}
    ports:
      - "${WEB_PORT}:80" # Apache web server
      - "${DEV_PORT}:8000" # Symfony or Laravel dev server (optional)
    volumes:
      - ./projects:/var/www/html/projects
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: ${PHPMYADMIN_CONTAINER_NAME}
  #   ports:
  #     - "${PHPMYADMIN_PORT}:80"
  #   environment:
  #     PMA_HOST: ${DB_SERVICE_NAME}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   depends_on:
  #     - db
